// Generated by gencpp from file altitude_sensor/sensor_data.msg
// DO NOT EDIT!


#ifndef ALTITUDE_SENSOR_MESSAGE_SENSOR_DATA_H
#define ALTITUDE_SENSOR_MESSAGE_SENSOR_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace altitude_sensor
{
template <class ContainerAllocator>
struct sensor_data_
{
  typedef sensor_data_<ContainerAllocator> Type;

  sensor_data_()
    : header()
    , altitude(0.0)
    , voltage(0.0)  {
    }
  sensor_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , altitude(0.0)
    , voltage(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _voltage_type;
  _voltage_type voltage;




  typedef boost::shared_ptr< ::altitude_sensor::sensor_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::altitude_sensor::sensor_data_<ContainerAllocator> const> ConstPtr;

}; // struct sensor_data_

typedef ::altitude_sensor::sensor_data_<std::allocator<void> > sensor_data;

typedef boost::shared_ptr< ::altitude_sensor::sensor_data > sensor_dataPtr;
typedef boost::shared_ptr< ::altitude_sensor::sensor_data const> sensor_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::altitude_sensor::sensor_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::altitude_sensor::sensor_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace altitude_sensor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'altitude_sensor': ['/home/me-547/catkin_ws_group10/src/me545-codes/lightware_alt_sensor/altitude_sensor/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::altitude_sensor::sensor_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::altitude_sensor::sensor_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::altitude_sensor::sensor_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::altitude_sensor::sensor_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::altitude_sensor::sensor_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::altitude_sensor::sensor_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::altitude_sensor::sensor_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "017a734bfa19419fd95b9ea7756925f7";
  }

  static const char* value(const ::altitude_sensor::sensor_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x017a734bfa19419fULL;
  static const uint64_t static_value2 = 0xd95b9ea7756925f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::altitude_sensor::sensor_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "altitude_sensor/sensor_data";
  }

  static const char* value(const ::altitude_sensor::sensor_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::altitude_sensor::sensor_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 altitude\n\
float64 voltage\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::altitude_sensor::sensor_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::altitude_sensor::sensor_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.altitude);
      stream.next(m.voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct sensor_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::altitude_sensor::sensor_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::altitude_sensor::sensor_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALTITUDE_SENSOR_MESSAGE_SENSOR_DATA_H
